"""empty message

Revision ID: 90aaa846f9d2
Revises: ed657e16ce20
Create Date: 2018-09-08 07:28:49.545376

"""

# revision identifiers, used by Alembic.
revision = '90aaa846f9d2'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
